import os
import sys
import argparse
import pandas as pd
import glob

from modules import statistical_testing
from globals import *

parser = argparse.ArgumentParser(description='Generate statistics for timeseries data')
parser.add_argument('--datatype', type=str, choices=['glitch', 'clean'], required=True, help='Type of data to process (glitch or clean)')
parser.add_argument('--band', type=str, choices=['full', 'low', 'high'], required=True, help='Frequency band to process')
parser.add_argument('--whitening_tw', type=int, default=10, help='Whitening time window in seconds (default: 10)')
parser.add_argument('--observation_tw', type=float, default=1.0, help='Observation time window in seconds (default: 1.0)')
parser.add_argument('--scaler_type', type=str, choices=['minmax', 'standard', 'robust', 'none'], default='standard', help='Type of scaler to use for statistics calculation (default: standard)')
parser.add_argument('--output_folder', type=str, default="./outputs", help='Folder to save the output results (default: ./outputs)')
args = parser.parse_args()

# Read all chunk files generated by fetch_timeseries.py
chunk_files = glob.glob(f"./temp/{args.datatype}_*.csv")

if not chunk_files:
    print(f"No chunk files found for {args.datatype} data type")
    sys.exit(1)

# Combine all chunks into a single DataFrame
data_chunks = []
for chunk_file in sorted(chunk_files):
    chunk_df = pd.read_csv(chunk_file)
    data_chunks.append(chunk_df)

combined_data = pd.concat(data_chunks, ignore_index=True)

# Filter out rows without timeseries files
combined_data = combined_data[combined_data['timeseries_filepath'].notna()]
combined_data = combined_data[combined_data['timeseries_filepath'] != '']
print(f"Processing {len(combined_data)} rows with valid timeseries files")

# Set band-specific parameters
if args.band == 'full':
    bandpass = False
    low_freq = 10
    high_freq = 1024
elif args.band == 'low':
    bandpass = True
    low_freq = 10
    high_freq = 512
elif args.band == 'high':
    bandpass = True
    low_freq = 512
    high_freq = 1024

output_file = f"{args.datatype}_{int(args.observation_tw)}s_{args.scaler_type}_statistical_results"

print(f"Processing {args.datatype} data for {args.band} frequency band...")
print(f"Bandpass: {bandpass}, Low Freq: {low_freq}, High Freq: {high_freq}")

# Process the timeseries using the unified function
statistical_testing.process_dataset(
    data=combined_data,
    datatype=args.datatype,
    whitening_tw=args.whitening_tw,
    observation_tw=args.observation_tw,
    srate=4096,
    ifo='L1',
    bandpass=bandpass,
    low_freq=low_freq,
    high_freq=high_freq,
    filter_before_whitening=False,
    output_file=output_file,
    output_folder=args.output_folder,
    scaler_type=args.scaler_type,
    postfix=args.band
)

print(f"Statistics generation complete for {args.datatype} {args.band} band. \n Results saved to {args.output_folder}/{output_file}_{args.band}.csv")